# %% 
full_dict = {
    "AAPL": "Apple Inc.",
    "MSFT": "Microsoft Corporation",
    "GOOGL": "Alphabet Inc. (Class A)",
    "AMZN": "Amazon.com Inc.",
    "TSLA": "Tesla Inc.",
    "META": "Meta Platforms Inc.",
    "NVDA": "NVIDIA Corporation",
    "BRK-A": "Berkshire Hathaway Inc. (Class A)",
    "JPM": "JPMorgan Chase & Co.",
    "V": "Visa Inc.",
    "JNJ": "Johnson & Johnson",
    "WMT": "Walmart Inc.",
    "PG": "Procter & Gamble Co.",
    "UNH": "UnitedHealth Group Incorporated",
    "MA": "Mastercard Incorporated",
    "DIS": "The Walt Disney Company",
    "HD": "The Home Depot Inc.",
    "BAC": "Bank of America Corporation",
    "XOM": "Exxon Mobil Corporation",
    "PFE": "Pfizer Inc.",
    "KO": "The Coca-Cola Company",
    "PEP": "PepsiCo Inc.",
    "CSCO": "Cisco Systems Inc.",
    "ADBE": "Adobe Inc.",
    "NFLX": "Netflix Inc.",
    "CMCSA": "Comcast Corporation",
    "NKE": "Nike Inc.",
    "ABT": "Abbott Laboratories",
    "T": "AT&T Inc.",
    "CRM": "Salesforce Inc.",
    "ORCL": "Oracle Corporation",
    "COST": "Costco Wholesale Corporation",
    "VZ": "Verizon Communications Inc.",
    "MRK": "Merck & Co., Inc.",
    "LLY": "Eli Lilly and Company",
    "INTC": "Intel Corporation",
    "CCI": "Crown Castle Inc.",
    "KR": "The Kroger Co.",
    "WBA": "Walgreens Boots Alliance Inc.",
    "BIIB": "Biogen Inc.",
    "BMY": "Bristol-Myers Squibb Company",
    "VRTX": "Vertex Pharmaceuticals Incorporated",
    "GILD": "Gilead Sciences Inc.",
    "EW": "Edwards Lifesciences Corporation",
    "ILMN": "Illumina Inc.",
    "ALGN": "Align Technology Inc.",
    "IQV": "IQVIA Holdings Inc.",
    "A": "Agilent Technologies Inc.",
    "D": "Dominion Energy Inc.",
    "ET": "Energy Transfer LP",
    "OKE": "ONEOK Inc.",
    "EPD": "Enterprise Products Partners L.P.",
    "KMI": "Kinder Morgan Inc.",
    "COP": "ConocoPhillips",
    "PSX": "Phillips 66",
    "EOG": "EOG Resources Inc.",
    "SLB": "Schlumberger Limited",
    "HAL": "Halliburton Company",
    "BKR": "Baker Hughes Company",
    "APA": "APA Corporation",
    "OXY": "Occidental Petroleum Corporation",
    "WMB": "The Williams Companies Inc.",
    "DTE": "DTE Energy Company",
    "AEE": "Ameren Corporation",
    "ES": "Eversource Energy",
    "CMS": "CMS Energy Corporation",
    "NI": "NiSource Inc.",
    "PCG": "PG&E Corporation",
    "SRE": "Sempra",
    "XEL": "Xcel Energy Inc.",
    "EIX": "Edison International",
    "VTR": "Ventas Inc.",
    "WELL": "Welltower Inc.",
    "ARE": "Alexandria Real Estate Equities Inc.",
    "HCA": "HCA Healthcare Inc.",
    "UHS": "Universal Health Services Inc.",
    "DGX": "Quest Diagnostics Incorporated",
    "LH": "Laboratory Corporation of America Holdings",
    "DVA": "DaVita Inc.",
    "ZN=F": "US 10-Year Treasury Note Futures",
    "ZF=F": "US 5-Year Treasury Note Futures",
    "ZT=F": "US 2-Year Treasury Note Futures",
    "ZB=F": "US 30-Year Treasury Bond Futures",
    "ZO=F": "French 10-Year OAT Futures",
    "BZ=F": "Brent Crude Oil Futures",
    "NG=F": "Natural Gas Futures",
    "RB=F": "RBOB Gasoline Futures",
    "HO=F": "Heating Oil Futures",
    "GC=F": "Gold Futures",
    "SI=F": "Silver Futures",
    "HG=F": "Copper Futures",
    "PL=F": "Platinum Futures",
    "PA=F": "Palladium Futures",
    "ZC=F": "Corn Futures",
    "ZS=F": "Soybean Futures",
    "ZW=F": "Wheat Futures",
    "KC=F": "Coffee Futures",
    "CT=F": "Cotton Futures",
    "SB=F": "Sugar Futures",
    "CC=F": "Cocoa Futures",
    "LE=F": "Live Cattle Futures",
    "GF=F": "Feeder Cattle Futures",
    "HE=F": "Lean Hogs Futures",
    "OJ=F": "Orange Juice Futures",
    "BTC-USD": "Bitcoin (BTC) / US Dollar",
    "ETH-USD": "Ethereum (ETH) / US Dollar",
    "BNB-USD": "Binance Coin (BNB) / US Dollar",
    "XRP-USD": "Ripple (XRP) / US Dollar",
    "ADA-USD": "Cardano (ADA) / US Dollar",
    "SOL-USD": "Solana (SOL) / US Dollar",
    "MATIC-USD": "Polygon (MATIC) / US Dollar",
    "SHIB-USD": "Shiba Inu (SHIB) / US Dollar",
    "LTC-USD": "Litecoin (LTC) / US Dollar",
    "AVAX-USD": "Avalanche (AVAX) / US Dollar",
    "LINK-USD": "Chainlink (LINK) / US Dollar",
    "XLM-USD": "Stellar (XLM) / US Dollar",
    "ATOM-USD": "Cosmos (ATOM) / US Dollar",
    "TRX-USD": "Tron (TRX) / US Dollar",
    "ETC-USD": "Ethereum Classic (ETC) / US Dollar",
    "AXS-USD": "Axie Infinity (AXS) / US Dollar",
    "FTM-USD": "Fantom (FTM) / US Dollar",
    "VET-USD": "VeChain (VET) / US Dollar",
    "THETA-USD": "Theta Network (THETA) / US Dollar",
    "XTZ-USD": "Tezos (XTZ) / US Dollar",
    "ENJ-USD": "Enjin Coin (ENJ) / US Dollar",
    "QNT-USD": "Quant (QNT) / US Dollar",
    "LDO-USD": "Lido DAO (LDO) / US Dollar",
    "BAT-USD": "Basic Attention Token (BAT) / US Dollar",
    "YFI-USD": "Yearn.Finance (YFI) / US Dollar",
    "SPY": "SPDR S&P 500 ETF",
    "QQQ": "Invesco QQQ ETF",
    "VTI": "Vanguard Total Stock Market ETF",
    "IVV": "iShares Core S&P 500 ETF",
    "VOO": "Vanguard S&P 500 ETF",
    "DIA": "SPDR Dow Jones Industrial Average ETF",
    "IWM": "iShares Russell 2000 ETF",
    "VTV": "Vanguard Value ETF",
    "VUG": "Vanguard Growth ETF",
    "ARKK": "ARK Innovation ETF",
    "TLT": "iShares 20+ Year Treasury Bond ETF",
    "LQD": "iShares iBoxx $ Investment Grade Corporate Bond ETF",
    "HYG": "iShares iBoxx $ High Yield Corporate Bond ETF",
    "EMB": "iShares J.P. Morgan USD Emerging Markets Bond ETF",
    "AGG": "iShares Core U.S. Aggregate Bond ETF",
    "BND": "Vanguard Total Bond Market ETF",
    "TIP": "iShares TIPS Bond ETF",
    "SHY": "iShares 1-3 Year Treasury Bond ETF",
    "IEF": "iShares 7-10 Year Treasury Bond ETF",
    "BIL": "SPDR Bloomberg 1-3 Month T-Bill ETF",
    "VNQ": "Vanguard Real Estate ETF",
    "XLRE": "Real Estate Select Sector SPDR Fund",
    "XLF": "Financial Select Sector SPDR Fund",
    "XLE": "Energy Select Sector SPDR Fund",
    "XLV": "Health Care Select Sector SPDR Fund",
    "XLY": "Consumer Discretionary Select Sector SPDR Fund",
    "XLP": "Consumer Staples Select Sector SPDR Fund",
    "XLK": "Technology Select Sector SPDR Fund",
    "XLI": "Industrial Select Sector SPDR Fund",
    "XLB": "Materials Select Sector SPDR Fund",
    "XLU": "Utilities Select Sector SPDR Fund",
    "ARKG": "ARK Genomic Revolution ETF",
    "ARKW": "ARK Next Generation Internet ETF",
    "ARKF": "ARK Fintech Innovation ETF",
    "ICLN": "iShares Global Clean Energy ETF",
    "TAN": "Invesco Solar ETF",
    "PBW": "Invesco WilderHill Clean Energy ETF",
    "URA": "Global X Uranium ETF",
    "LIT": "Global X Lithium & Battery Tech ETF",
    "SOXX": "iShares Semiconductor ETF",
    "XBI": "SPDR S&P Biotech ETF",
    "IBB": "iShares Biotechnology ETF",
    "EFA": "iShares MSCI EAFE ETF",
    "EEM": "iShares MSCI Emerging Markets ETF",
    "VWO": "Vanguard FTSE Emerging Markets ETF",
    "GLD": "SPDR Gold Shares ETF",
    "SLV": "iShares Silver Trust ETF",
    "^TNX":"CBOE Interest Rate 10 Year T No",
}

full_categories_dict = {
    "AAPL": "Equity",
    "MSFT": "Equity",
    "GOOGL": "Equity",
    "AMZN": "Equity",
    "TSLA": "Equity",
    "META": "Equity",
    "NVDA": "Equity",
    "BRK-A": "Equity",
    "JPM": "Equity",
    "V": "Equity",
    "JNJ": "Equity",
    "WMT": "Equity",
    "PG": "Equity",
    "UNH": "Equity",
    "MA": "Equity",
    "DIS": "Equity",
    "HD": "Equity",
    "BAC": "Equity",
    "XOM": "Equity",
    "PFE": "Equity",
    "KO": "Equity",
    "PEP": "Equity",
    "CSCO": "Equity",
    "ADBE": "Equity",
    "NFLX": "Equity",
    "CMCSA": "Equity",
    "NKE": "Equity",
    "ABT": "Equity",
    "T": "Equity",
    "CRM": "Equity",
    "ORCL": "Equity",
    "COST": "Equity",
    "VZ": "Equity",
    "MRK": "Equity",
    "LLY": "Equity",
    "INTC": "Equity",
    "CCI": "Equity",
    "KR": "Equity",
    "WBA": "Equity",
    "BIIB": "Equity",
    "BMY": "Equity",
    "VRTX": "Equity",
    "GILD": "Equity",
    "EW": "Equity",
    "ILMN": "Equity",
    "ALGN": "Equity",
    "IQV": "Equity",
    "A": "Equity",
    "D": "Equity",
    "ET": "Equity",
    "OKE": "Equity",
    "EPD": "Equity",
    "KMI": "Equity",
    "COP": "Equity",
    "PSX": "Equity",
    "EOG": "Equity",
    "SLB": "Equity",
    "HAL": "Equity",
    "BKR": "Equity",
    "APA": "Equity",
    "OXY": "Equity",
    "WMB": "Equity",
    "DTE": "Equity",
    "AEE": "Equity",
    "ES": "Equity",
    "CMS": "Equity",
    "NI": "Equity",
    "PCG": "Equity",
    "SRE": "Equity",
    "XEL": "Equity",
    "EIX": "Equity",
    "VTR": "Equity",
    "WELL": "Equity",
    "ARE": "Equity",
    "HCA": "Equity",
    "UHS": "Equity",
    "DGX": "Equity",
    "LH": "Equity",
    "DVA": "Equity",
    "ZN=F": "Bond",
    "ZF=F": "Bond",
    "ZT=F": "Bond",
    "ZB=F": "Bond",
    "ZO=F": "Bond",
    "BZ=F": "Commodities",
    "NG=F": "Commodities",
    "RB=F": "Commodities",
    "HO=F": "Commodities",
    "GC=F": "Commodities",
    "SI=F": "Commodities",
    "HG=F": "Commodities",
    "PL=F": "Commodities",
    "PA=F": "Commodities",
    "ZC=F": "Commodities",
    "ZS=F": "Commodities",
    "ZW=F": "Commodities",
    "KC=F": "Commodities",
    "CT=F": "Commodities",
    "SB=F": "Commodities",
    "CC=F": "Commodities",
    "LE=F": "Commodities",
    "GF=F": "Commodities",
    "HE=F": "Commodities",
    "OJ=F": "Commodities",
    "BTC-USD": "Crypto",
    "ETH-USD": "Crypto",
    "BNB-USD": "Crypto",
    "XRP-USD": "Crypto",
    "ADA-USD": "Crypto",
    "SOL-USD": "Crypto",
    "MATIC-USD": "Crypto",
    "SHIB-USD": "Crypto",
    "LTC-USD": "Crypto",
    "AVAX-USD": "Crypto",
    "LINK-USD": "Crypto",
    "XLM-USD": "Crypto",
    "ATOM-USD": "Crypto",
    "TRX-USD": "Crypto",
    "ETC-USD": "Crypto",
    "AXS-USD": "Crypto",
    "FTM-USD": "Crypto",
    "VET-USD": "Crypto",
    "THETA-USD": "Crypto",
    "XTZ-USD": "Crypto",
    "ENJ-USD": "Crypto",
    "QNT-USD": "Crypto",
    "LDO-USD": "Crypto",
    "BAT-USD": "Crypto",
    "YFI-USD": "Crypto",
    "US5Y": "Bond",
    "DE10Y": "Bond",
    "FR10Y": "Bond",
    "IT10Y": "Bond",
    "UK10Y": "Bond",
    "JP10Y": "Bond",
    "CA10Y": "Bond",
    "AU10Y": "Bond",
    "BR10Y": "Bond",
    "IN10Y": "Bond",
    "SE10Y": "Bond",
    "FI10Y": "Bond",
    "NO10Y": "Bond",
    "NZ10Y": "Bond",
    "AMT": "Bond",
    "IBM": "Bond",
    "GE": "Bond",
    "T": "Bond",
    "VZ": "Bond",
    "DIS": "Bond",
    "GM": "Bond",
    "PG": "Bond",
    "KO": "Bond",
    "PEP": "Bond",
    "CVX": "Bond",
    "PFE": "Bond",
    "BMY": "Bond",
    "JNJ": "Bond",
    "HD": "Bond",
    "WMT": "Bond",
    "AAPL": "Bond",
    "MSFT": "Bond",
    "AMZN": "Bond",
    "TSLA": "Bond",
    "SPY": "ETF",
    "IVV": "ETF",
    "VOO": "ETF",
    "IWM": "ETF",
    "EEM": "ETF",
    "VTI": "ETF",
    "QQQ": "ETF",
    "XLF": "ETF",
    "XLY": "ETF",
    "XLC": "ETF",
    "XLI": "ETF",
    "XLE": "ETF",
    "XLB": "ETF",
    "XTL": "ETF",
    "GDX": "ETF",
    "GLD": "ETF",
    "SLV": "ETF",
    "LQD": "ETF",
    "BND": "ETF",
    "AGG": "ETF",
    "TIP": "ETF",
    "HYG": "ETF",
    "TLT": "ETF",
    "IYR": "ETF",
    "VNQ": "ETF",
    "VYM": "ETF",
    "SCHD": "ETF",
    "^TNX":"Taux",
}

full_dict_category = {
    "AAPL": "Equity",
    "MSFT": "Equity",
    "GOOGL": "Equity",
    "AMZN": "Equity",
    "TSLA": "Equity",
    "META": "Equity",
    "NVDA": "Equity",
    "BRK-A": "Equity",
    "JPM": "Equity",
    "V": "Equity",
    "JNJ": "Equity",
    "WMT": "Equity",
    "PG": "Equity",
    "UNH": "Equity",
    "MA": "Equity",
    "DIS": "Equity",
    "HD": "Equity",
    "BAC": "Equity",
    "XOM": "Equity",
    "PFE": "Equity",
    "KO": "Equity",
    "PEP": "Equity",
    "CSCO": "Equity",
    "ADBE": "Equity",
    "NFLX": "Equity",
    "CMCSA": "Equity",
    "NKE": "Equity",
    "ABT": "Equity",
    "T": "Equity",
    "CRM": "Equity",
    "ORCL": "Equity",
    "COST": "Equity",
    "VZ": "Equity",
    "MRK": "Equity",
    "LLY": "Equity",
    "INTC": "Equity",
    "CCI": "Equity",
    "KR": "Equity",
    "WBA": "Equity",
    "BIIB": "Equity",
    "BMY": "Equity",
    "VRTX": "Equity",
    "GILD": "Equity",
    "EW": "Equity",
    "ILMN": "Equity",
    "ALGN": "Equity",
    "IQV": "Equity",
    "A": "Equity",
    "D": "Equity",
    "ET": "Equity",
    "OKE": "Equity",
    "EPD": "Equity",
    "KMI": "Equity",
    "COP": "Equity",
    "PSX": "Equity",
    "EOG": "Equity",
    "SLB": "Equity",
    "HAL": "Equity",
    "BKR": "Equity",
    "APA": "Equity",
    "OXY": "Equity",
    "WMB": "Equity",
    "DTE": "Equity",
    "AEE": "Equity",
    "ES": "Equity",
    "CMS": "Equity",
    "NI": "Equity",
    "PCG": "Equity",
    "SRE": "Equity",
    "XEL": "Equity",
    "EIX": "Equity",
    "VTR": "Equity",
    "WELL": "Equity",
    "ARE": "Equity",
    "HCA": "Equity",
    "UHS": "Equity",
    "DGX": "Equity",
    "LH": "Equity",
    "DVA": "Equity",
    "ZN=F": "Bond",
    "ZF=F": "Bond",
    "ZT=F": "Bond",
    "ZB=F": "Bond",
    "ZO=F": "Bond",
    "BZ=F": "Commodities",
    "NG=F": "Commodities",
    "RB=F": "Commodities",
    "HO=F": "Commodities",
    "GC=F": "Commodities",
    "SI=F": "Commodities",
    "HG=F": "Commodities",
    "PL=F": "Commodities",
    "PA=F": "Commodities",
    "ZC=F": "Commodities",
    "ZS=F": "Commodities",
    "ZW=F": "Commodities",
    "KC=F": "Commodities",
    "CT=F": "Commodities",
    "SB=F": "Commodities",
    "CC=F": "Commodities",
    "LE=F": "Commodities",
    "GF=F": "Commodities",
    "HE=F": "Commodities",
    "OJ=F": "Commodities",
    "BTC-USD": "Crypto",
    "ETH-USD": "Crypto",
    "BNB-USD": "Crypto",
    "XRP-USD": "Crypto",
    "ADA-USD": "Crypto",
    "SOL-USD": "Crypto",
    "MATIC-USD": "Crypto",
    "SHIB-USD": "Crypto",
    "LTC-USD": "Crypto",
    "AVAX-USD": "Crypto",
    "LINK-USD": "Crypto",
    "XLM-USD": "Crypto",
    "ATOM-USD": "Crypto",
    "TRX-USD": "Crypto",
    "ETC-USD": "Crypto",
    "AXS-USD": "Crypto",
    "FTM-USD": "Crypto",
    "VET-USD": "Crypto",
    "THETA-USD": "Crypto",
    "XTZ-USD": "Crypto",
    "ENJ-USD": "Crypto",
    "QNT-USD": "Crypto",
    "LDO-USD": "Crypto",
    "BAT-USD": "Crypto",
    "YFI-USD": "Crypto",
    "US5Y": "Bond",
    "DE10Y": "Bond",
    "FR10Y": "Bond",
    "IT10Y": "Bond",
    "UK10Y": "Bond",
    "JP10Y": "Bond",
    "CA10Y": "Bond",
    "AU10Y": "Bond",
    "BR10Y": "Bond",
    "IN10Y": "Bond",
    "SE10Y": "Bond",
    "FI10Y": "Bond",
    "NO10Y": "Bond",
    "NZ10Y": "Bond",
    "AMT": "Bond",
    "IBM": "Bond",
    "GE": "Bond",
    "T": "Bond",
    "VZ": "Bond",
    "DIS": "Bond",
    "GM": "Bond",
    "PG": "Bond",
    "KO": "Bond",
    "PEP": "Bond",
    "CVX": "Bond",
    "PFE": "Bond",
    "BMY": "Bond",
    "JNJ": "Bond",
    "HD": "Bond",
    "WMT": "Bond",
    "AAPL": "Bond",
    "MSFT": "Bond",
    "AMZN": "Bond",
    "TSLA": "Bond",
    "SPY": "ETF",
    "IVV": "ETF",
    "VOO": "ETF",
    "IWM": "ETF",
    "EEM": "ETF",
    "VTI": "ETF",
    "QQQ": "ETF",
    "XLF": "ETF",
    "XLY": "ETF",
    "XLC": "ETF",
    "XLI": "ETF",
    "XLE": "ETF",
    "XLB": "ETF",
    "XTL": "ETF",
    "GDX": "ETF",
    "GLD": "ETF",
    "SLV": "ETF",
    "LQD": "ETF",
    "BND": "ETF",
    "AGG": "ETF",
    "TIP": "ETF",
    "HYG": "ETF",
    "TLT": "ETF",
    "IYR": "ETF",
    "VNQ": "ETF",
    "VYM": "ETF",
    "SCHD": "ETF",
    "^TNX":"Taux",
}
# %%
